apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservice
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: microservice
  namespaceSelector:
    matchNames:
      - microservices
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
