grafana:
  service:
    type: ClusterIP
  resources:
    requests: { cpu: 50m, memory: 128Mi }
    limits:   { cpu: 200m, memory: 256Mi }

prometheus:
  prometheusSpec:
    resources:
      requests: { cpu: 100m, memory: 256Mi }
      limits:   { cpu: 300m, memory: 512Mi }
