apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: microservices
  labels:
    app: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 0
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: app
          image: acrmsvc012345.azurecr.io/microservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: PORT
              value: "5000"
          readinessProbe:
            httpGet:
              path: /products      # app has /products endpoint
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /products
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      affinity:
        podAntiAffinity:               # ensures pods spread across nodes
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - microservice
              topologyKey: "kubernetes.io/hostname"
