name: Build & Deploy to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

env:
  IMAGE_NAME: microservice

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Install kubelogin
        run: |
          az aks install-cli
          kubelogin --version

      - name: Docker login to ACR
        run: az acr login -n ${{ secrets.ACR_LOGIN_SERVER }}


      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./application
          file: ./application/Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          
      - name: Convert kubeconfig for azurecli exec
        run: |
          # aks-set-context sets KUBECONFIG to the temp file it created
          echo "Using kubeconfig: $KUBECONFIG"
          kubelogin convert-kubeconfig -l azurecli --kubeconfig "$KUBECONFIG"

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Create namespace (idempotent)
        run: |
          kubectl apply -f k8s/namespace.yaml

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/

      - name: Update image to new SHA
        run: |
          kubectl -n microservices set image deployment/microservice app=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Wait for rollout
        run: |
          kubectl -n microservices rollout status deploy/microservice --timeout=180s

      - name: Show service external IP
        run: |
          kubectl -n microservices get svc microservice -o wide
